// src/services/ai-marking/MarkingSanitizer.ts

/**
 * THE IRON DOME (V3): Pure Safety
 * Guarantees that marks are PRESERVED, only bad links are SEVERED.
 */
export function sanitizeAnnotations(
    rawAnnotations: any[],
    ocrBlocks: any[]
): any[] {
    console.log('🛡️ [IRON DOME V3] Scanning for False Positives...');

    if (!Array.isArray(rawAnnotations) || rawAnnotations.length === 0) {
        return [];
    }

    return rawAnnotations.map(anno => {
        // 1. SAFETY: If already UNMATCHED, force line_id to null and PASS.
        // This ensures we keep "Ghost Marks" generated by the AI.
        if (anno.ocr_match_status !== 'MATCHED') {
            if (anno.line_id) {
                return { ...anno, line_id: null }; // Clean up messy unmatched
            }
            return anno;
        }

        // 2. CHECK: Does the ID exist?
        // If not, KEEP THE MARK but set to UNMATCHED.
        // We prioritize linked_ocr_id which is the physical evidence ID.
        // Support both underscore and camelCase from AI
        const linkedId = anno.linked_ocr_id || anno.linkedOcrId || anno.linked_id;
        const searchId = linkedId || anno.line_id;

        if (!searchId) {
            return { ...anno, ocr_match_status: 'UNMATCHED' };
        }

        const block = ocrBlocks.find((b: any) => b.id === searchId);
        if (!block) {
            console.warn(`⚠️ [IRON DOME] Block ID '${searchId}' not found in OCR list. Switching to UNMATCHED.`);
            return { ...anno, ocr_match_status: 'UNMATCHED', line_id: null, linked_ocr_id: null, linkedOcrId: null };
        }

        // 3. DIGIT FIDELITY CHECK
        // Logic: If the student answer implies numbers that aren't in the block, it's a false match.
        // We VETO the LINK, but we KEEP THE MARK.
        const studentText = (anno.student_text || anno.studentText || "").toString();
        const ocrText = block.text.toString();

        const studentDigits = [...new Set(studentText.match(/\d/g) || [])];

        for (const digit of studentDigits) {
            if (!ocrText.includes(digit)) {
                console.log(`🛡️ [IRON DOME] BLOCKED False Positive!`);
                console.log(`   ❌ Student has digit '${digit}' ("${studentText}")`);
                console.log(`   ❌ OCR Block MISSES digit '${digit}' ("${ocrText}")`);
                console.log(`   👉 Action: UNLINK (Keep Mark, remove ID)`);

                return {
                    ...anno,
                    ocr_match_status: 'UNMATCHED',
                    line_id: null, // Sever the link
                    reasoning: `${anno.reasoning} [SYSTEM: Linked removed due to mismatch]`
                };
            }
        }

        // If passed all checks, return original
        return anno;
    });
}